# Generated by Django 5.0.2 on 2024-02-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(default=500.0)),
                ('prod_img', models.ImageField(blank=True, default=True, null=True, upload_to='img')),
                ('description', models.TextField(blank=True, null=True)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(default=None)),
            ],
        ),
    ]
