# Generated by Django 5.0.2 on 2024-03-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='review_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
