# Generated by Django 5.0.2 on 2024-03-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_reviewrating_review_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='review_id',
        ),
    ]
