# Generated by Django 5.0.2 on 2024-03-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_reviewrating_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='review',
            field=models.CharField(default='Default review text', max_length=400),
        ),
    ]
