# Generated by Django 5.0.2 on 2024-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_reviewrating_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ratings',
        ),
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
