# Generated by Django 5.0.2 on 2024-03-11 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='average_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='prod_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='prod_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
