# Generated by Django 5.0.2 on 2024-03-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cartitem_average_rating_cartitem_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='prod_img',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='prod_name',
        ),
    ]
