# Generated by Django 5.0.2 on 2024-03-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_product_id_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
