# Generated by Django 5.0.2 on 2024-03-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_product_id_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='product_id',
        ),
    ]
